### **Basic Array Operations**

In [1]:
import numpy as np
arr1 =  np.array([5,6,7]) # 1-D array
print("arr1 is",arr1.ndim,"D array")

arr2 = np.array([[1,2],[3,4],[5,6]]) # 2-D array
print("arr2 is",arr2.ndim,"D array")

print("size of element of arr1 is",arr1.itemsize,"bytes")
print("datatype of arr1 is",arr1.dtype)
print("size of arr2 is",arr2.size)

arr1 is 1 D array
arr2 is 2 D array
size of element of arr1 is 8 bytes
datatype of arr1 is int64
size of arr2 is 6


In [2]:
arr3 = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print("size of element of arr3 is",arr3.itemsize,"bytes")
print("datatype of arr3 is",arr3.dtype)
print("dimensions of arr3 are",arr3.shape)

arr4 = np.array([[1,2],[3,4],[5,6]], dtype=complex)
print(arr4)

size of element of arr3 is 8 bytes
datatype of arr3 is float64
dimensions of arr3 are (3, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [3]:
arr5 = np.zeros((3,5)) # array initialized with zeroes with specific shape/dimensions
print(arr5)
arr6 = np.ones((3,2)) # array initialized with ones with specific shape/dimensions
print(arr6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
arr7 = np.arange(1,10,2) #(start,stop,step) # here, 10 is not included
print(arr7)

arr8 = np.linspace(1,5,10) # generates 10 linearly spaced numbers b/w 1 and 5\
print(arr8)

[1 3 5 7 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [5]:
print(arr2)
print(arr2.reshape(2,3))

print(arr2.ravel()) # to flaten the multidimensional array

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [6]:
print(arr1.min())
print(arr1.max())
print(arr1.sum())

# axis 0 is column-wise and axis 1 is row-wise
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

print(np.sqrt(arr2)) # square root
print(np.std(arr2)) # standard deviation

5
7
18
[ 9 12]
[ 3  7 11]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
1.707825127659933


In [7]:
a1 = np.array([[1,2],[3,2]])
a2 = np.array([[4,5],[6,5]])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1.dot(a2))

[[5 7]
 [9 7]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [18 10]]
[[0.25 0.4 ]
 [0.5  0.4 ]]
[[16 15]
 [24 25]]
